services:
  email-service:
    image: altafino/email-extractor:latest
    command: sh -c "ls -la /app/config && ls -la /app/config/templates && /app/email-service"
    ports:
      - "9999:8080"
    volumes:
      - ./config:/app/config
      - attachment-data:/data/attachments
    environment:
      - CONFIG_PATH=/app/config/default.config.yaml
      - TZ=UTC
      - DEBUG=true
      - LOG_LEVEL=debug
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  attachment-data:
   