services:
  email-service:
    image: altafino/email-extractor:latest
    ports:
      - "9999:8080"
    volumes:
      - type: bind
        source: /opt/email-extractor/config/templates/base.yaml
        target: /app/config/templates/base.yaml
        read_only: true
      - type: bind
        source: /opt/email-extractor/config/account1.config.yaml
        target: /app/config/account1.config.yaml
        read_only: true
      - type: bind
        source: /opt/email-extractor/config/account2.config.yaml
        target: /app/config/account2.config.yaml
        read_only: true
      - attachment-data:/data/attachments
    environment:
      - TZ=UTC
      - DEBUG=true
      - LOG_LEVEL=debug
      - CONFIG_FILES=account1.config.yaml,account2.config.yaml
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  attachment-data:
   