meta:
  id: "default"
  name: "Default Configuration"
  description: "Default email extraction configuration changed"
  template: "base"
  enabled: true

server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: 30
  write_timeout: 30
  idle_timeout: 60

email:
  default_timeout: 300
  rate_limit: 100
  max_concurrent: 5
  protocols:
    imap:
      enabled: false
      default_port: 993
      insecure_port: 143
      idle_timeout: 60
      batch_size: 100
    pop3:
      enabled: true
      default_port: 995
      insecure_port: 110
      server: "email-ssl.com.br"  # Example for Gmail POP3
      username: "ah@ecogotas.com.br" #"${POP3_USERNAME}"  # Will be replaced with environment variable
      password: "H4ld3m4nn76@!" #"${POP3_PASSWORD}"  # Will be replaced with environment variable
      delete_after_download: false
  security:
    tls:
      enabled: true
      min_version: "1.2"
      verify_cert: true
      cert_file: ""  # Optional client certificate
      key_file: ""   # Optional client key
    oauth2:
      enabled: false
      providers:
        google:
          client_id: ""
          client_secret: ""
          redirect_url: "http://localhost:8080/auth/callback"
          auth_url: "https://accounts.google.com/o/oauth2/auth"
          token_url: "https://oauth2.googleapis.com/token"
          scopes:
            - "https://mail.google.com/"
        microsoft:
          client_id: ""
          client_secret: ""
          redirect_url: "http://localhost:8080/auth/callback"
          auth_url: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize"
          token_url: "https://login.microsoftonline.com/common/oauth2/v2.0/token"
          scopes:
            - "https://outlook.office.com/IMAP.AccessAsUser.All"
            - "https://outlook.office.com/POP.AccessAsUser.All"
            - "offline_access"
  retry:
    max_attempts: 3
    delay: 5
  attachments:
    allowed_types:
      - ".jpg"
      - ".jpeg"
      - ".png"
      - ".gif"
      - ".pdf"
      - ".xml"
      - ".xlsx"
      - ".xls"
      - ".doc"
      - ".docx"
      - ".ppt"
      - ".pptx"
      - ".txt"
      - ".csv"
      - ".zip"
      - ".rar"
      - ".7z"
      - ".rtf"
    max_size: 26214400  # 25MB in bytes
    storage_path: "/home/stefan/data/attachments"
    naming_pattern: "${filename}"
    preserve_structure: true
    scan_nested: true
    sanitize_filenames: true
    handle_duplicates: "increment"

security:
  allowed_ips:
    - "127.0.0.1"
    - "::1"
  api_keys:
    - "test-key-1234567890abcdef"
  cors:
    enabled: true
    allowed_origins:
      - "http://localhost:3000"
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
    allowed_headers:
      - "Authorization"
      - "Content-Type"
    expose_headers:
      - "X-Request-ID"
    max_age: 3600
    allow_credentials: true
  rate_limiting:
    enabled: true
    requests_per_second: 10
    burst: 50

logging:
  level: "debug"  # debug, info, warn, error
  format: "json" # json, text
  output: "stdout"  # stdout, file
  file_path: "/var/log/email-extractor.log"
  include_caller: true
  redact_sensitive: true
  rotation:
    enabled: true
    max_size: 100  # MB
    max_age: 30    # days
    max_backups: 5
    compress: true

monitoring:
  metrics_enabled: true
  metrics_path: "/metrics"
  health_check_path: "/health"
  tracing:
    enabled: true
    exporter: "jaeger"
    endpoint: "http://jaeger:14268/api/traces"
    sample_rate: 0.1
  profiling:
    enabled: true
    path: "/debug/pprof"
  alerts:
    enabled: true
    endpoints:
      - type: "slack"
        url: "https://hooks.slack.com/services/xxx/yyy/zzz"
      - type: "email"
        address: "alerts@example.com"
    thresholds:
      error_rate: 0.01
      response_time_ms: 1000
      disk_usage_percent: 90

scheduling:
  enabled: true
  frequency_every: "minute"
  frequency_amount: 3
  start_now: true
  start_at: "2024-03-15T00:00:00Z"
  stop_at: "2025-12-31T23:59:59Z"

# ... rest of the configuration remains the same ... 