# Base template for email extractor configurations
meta:
  id: "base"
  name: "Base Template"
  description: "Base template for email extraction configuration"
  template: ""
  enabled: true

server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: 30
  write_timeout: 30
  idle_timeout: 60

email:
  default_timeout: 300
  rate_limit: 100
  max_concurrent: 5
  protocols:
    imap:
      enabled: false
      default_port: 993
      insecure_port: 143
      idle_timeout: 60
      batch_size: 100
      server: "${IMAP_SERVER}"
      username: "${IMAP_USERNAME}"
      password: "${IMAP_PASSWORD}"
      folders: ["INBOX"]
      use_idle: false
      delete_after_download: false
      security:
        tls:
          enabled: true
          min_version: "1.2"
          verify_cert: true
          cert_file: ""
          key_file: ""
        oauth2:
          enabled: false
          provider: "google"
          client_id: "${OAUTH_CLIENT_ID}"
          client_secret: "${OAUTH_CLIENT_SECRET}"
    pop3:
      enabled: false
      default_port: 995
      insecure_port: 110
      server: "${POP3_SERVER}"
      username: "${POP3_USERNAME}"
      password: "${POP3_PASSWORD}"
      delete_after_download: false
      security:
        tls:
          enabled: true
          min_version: "1.2"
          verify_cert: true
          cert_file: ""
          key_file: ""
        oauth2:
          enabled: false
          provider: "google"
          client_id: "${OAUTH_CLIENT_ID}"
          client_secret: "${OAUTH_CLIENT_SECRET}"
      date_filter:
        enabled: false
        from: ""  # ISO8601 format: "2023-01-01T00:00:00Z"
        to: ""    # ISO8601 format: "2023-12-31T23:59:59Z"
  retry:
    max_attempts: 3
    delay: 5
  attachments:
    allowed_types:
      - ".pdf"
      - ".xml"
      - ".xlsx"
      - ".xls"
      - ".doc"
      - ".docx"
      - ".txt"
      - ".csv"
    max_size: 104857600
    storage_path: "/home/stefan/data/attachments/${YYYY}/${MM}/${DD}"
    naming_pattern: "${unixtime}_${filename}"
    preserve_structure: true
    scan_nested: true
    sanitize_filenames: true
    handle_duplicates: "increment"
    storage:
      type: "gdrive"
      credentials_file: "/home/stefan/data/credentials.json"
      parent_folder_id: "1234567890abcdef"
  tracking:
    enabled: false
    storage_type: "file"
    storage_path: "/data/tracking"
    retention_days: 30
    tracking_format: "json"
    track_downloaded: true
  error_logging:
    enabled: true
    storage_type: "file"
    storage_path: "/data/error_logs"
    retention_days: 30
    log_raw_message: false

security:
  allowed_ips:
    - "127.0.0.1"
    - "::1"
  api_keys: []
  cors:
    enabled: true
    allowed_origins:
      - "http://localhost:3000"
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
    allowed_headers:
      - "Authorization"
      - "Content-Type"
    expose_headers:
      - "X-Request-ID"
    max_age: 3600
    allow_credentials: true
  rate_limiting:
    enabled: true
    requests_per_second: 10
    burst: 50

logging:
  level: "info"
  format: "json"
  output: "stdout"
  file_path: "${LOG_FILE_PATH}"
  include_caller: true
  redact_sensitive: true
  rotation:
    enabled: true
    max_size: 100
    max_age: 30
    max_backups: 5
    compress: true

monitoring:
  metrics_enabled: true
  metrics_path: "/metrics"
  health_check_path: "/health"
  tracing:
    enabled: true
    exporter: "jaeger"
    endpoint: "${JAEGER_ENDPOINT}"
    sample_rate: 0.1
  profiling:
    enabled: true
    path: "/debug/pprof"
  alerts:
    enabled: true
    endpoints:
      - type: "email"
        address: "${ALERT_EMAIL}"
    thresholds:
      error_rate: 0.01
      response_time_ms: 1000
      disk_usage_percent: 90

scheduling:
  enabled: true
  frequency_every: "minute"
  frequency_amount: 30
  start_now: true
  start_at: "2024-03-15T00:00:00Z"  # RFC3339 format
  stop_at: "2025-12-31T23:59:59Z"   # RFC3339 format 