# Base template for email extractor configurations
meta:
  id: "base"
  name: "Base Template"
  description: "Base template for email extraction configuration"
  template: ""
  enabled: true

server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: 30
  write_timeout: 30
  idle_timeout: 60

email:
  default_timeout: 300
  rate_limit: 100
  max_concurrent: 5
  protocols:
    imap:
      enabled: false
      default_port: 993
      insecure_port: 143
      idle_timeout: 60
      batch_size: 100
    pop3:
      enabled: true
      default_port: 995
      insecure_port: 110
      server: "${POP3_SERVER}"
      username: "${POP3_USERNAME}"
      password: "${POP3_PASSWORD}"
      delete_after_download: false
  security:
    tls:
      enabled: true
      min_version: "1.2"
      verify_cert: true
      cert_file: ""
      key_file: ""
    oauth2:
      enabled: false
      providers: {}
  retry:
    max_attempts: 3
    delay: 5
  attachments:
    allowed_types:
      - ".pdf"
      - ".xml"
      - ".xlsx"
      - ".xls"
      - ".doc"
      - ".docx"
      - ".txt"
      - ".csv"
    max_size: 104857600
    storage_path: "/data/attachments"
    naming_pattern: "${unixtime}_${filename}"
    preserve_structure: true
    scan_nested: true
    sanitize_filenames: true
    handle_duplicates: "increment"

security:
  allowed_ips:
    - "127.0.0.1"
    - "::1"
  api_keys: []
  cors:
    enabled: true
    allowed_origins:
      - "http://localhost:3000"
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
    allowed_headers:
      - "Authorization"
      - "Content-Type"
    expose_headers:
      - "X-Request-ID"
    max_age: 3600
    allow_credentials: true
  rate_limiting:
    enabled: true
    requests_per_second: 10
    burst: 50

logging:
  level: "info"
  format: "json"
  output: "stdout"
  file_path: "${LOG_FILE_PATH}"
  include_caller: true
  redact_sensitive: true
  rotation:
    enabled: true
    max_size: 100
    max_age: 30
    max_backups: 5
    compress: true

monitoring:
  metrics_enabled: true
  metrics_path: "/metrics"
  health_check_path: "/health"
  tracing:
    enabled: true
    exporter: "jaeger"
    endpoint: "${JAEGER_ENDPOINT}"
    sample_rate: 0.1
  profiling:
    enabled: true
    path: "/debug/pprof"
  alerts:
    enabled: true
    endpoints:
      - type: "email"
        address: "${ALERT_EMAIL}"
    thresholds:
      error_rate: 0.01
      response_time_ms: 1000
      disk_usage_percent: 90

scheduling:
  enabled: true
  frequency_every: "minute"
  frequency_amount: 5
  start_now: true
  start_at: ""  # UTC DateTime (2006-01-02T15:04:05Z)
  stop_at: ""   # UTC DateTime (2006-01-02T15:04:05Z) 