# Base template for email extractor configurations
meta:
  enabled: true

server:
  host: "0.0.0.0"
  read_timeout: 30
  write_timeout: 30
  idle_timeout: 60

email:
  default_timeout: 300
  rate_limit: 100
  max_concurrent: 5
  protocols:
    imap:
      enabled: true
      default_port: 993
      insecure_port: 143
      idle_timeout: 60
      batch_size: 100
    pop3:
      enabled: true
      default_port: 995
      insecure_port: 110
      delete_after_download: false
  security:
    tls:
      enabled: true
      min_version: "1.2"
      verify_cert: true
    oauth2:
      enabled: false
      providers:
        google:
          auth_url: "https://accounts.google.com/o/oauth2/auth"
          token_url: "https://oauth2.googleapis.com/token"
          scopes:
            - "https://mail.google.com/"
        microsoft:
          auth_url: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize"
          token_url: "https://login.microsoftonline.com/common/oauth2/v2.0/token"
          scopes:
            - "https://outlook.office.com/IMAP.AccessAsUser.All"
            - "https://outlook.office.com/POP.AccessAsUser.All"
            - "offline_access"
  retry:
    max_attempts: 3
    delay: 5
  attachments:
    allowed_types:
      - ".pdf"
      - ".docx"
      - ".xlsx"
      - ".zip"
      - ".jpg"
      - ".jpeg"
      - ".png"
      - ".txt"
      - ".csv"
    max_size: 26214400  # 25MB in bytes
    naming_pattern: "${unixtime}_${filename}"
    preserve_structure: true
    scan_nested: true
    sanitize_filenames: true

security:
  allowed_ips:
    - "127.0.0.1"
    - "::1"
  cors:
    enabled: true
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
    allowed_headers:
      - "Authorization"
      - "Content-Type"
    expose_headers:
      - "X-Request-ID"
    max_age: 3600
    allow_credentials: true
  rate_limiting:
    enabled: true
    requests_per_second: 10
    burst: 50

logging:
  level: "info"
  format: "json"
  output: "stdout"
  include_caller: true
  redact_sensitive: true
  rotation:
    enabled: true
    max_size: 100  # MB
    max_age: 30    # days
    max_backups: 5
    compress: true

monitoring:
  metrics_enabled: true
  health_check_path: "/health"
  tracing:
    enabled: false
    sample_rate: 0.1
  profiling:
    enabled: true
    path: "/debug/pprof"
  alerts:
    enabled: true
    thresholds:
      error_rate: 0.01
      response_time_ms: 1000
      disk_usage_percent: 90

scheduling:
  enabled: true
  frequency_every: "hour"  # minute, hour, day, week, month
  frequency_amount: 1
  start_now: true
  start_at: ""  # UTC DateTime (2006-01-02T15:04:05Z)
  stop_at: ""   # UTC DateTime (2006-01-02T15:04:05Z) 